### ISSUE TITLE
Ingest latency for S3 bucket

### ISSUE THREAD

**Issue by JTuckerBCAE** [aws-samples/aws-stf-core#3]
Hi,

I have have been experimenting with the stf-core, and so far I am loving its ease of implementation.
I have deployed an [stf-core-scorpio](https://github.com/aws-samples/aws-stf-core-scorpio) stack along side the [LoRaWAN data producer](https://github.com/aws-samples/aws-stf-dp-aicl) and the [Athena Data consumer](https://github.com/aws-samples/aws-stf-dc-athena).

So far all my LoRaWAN uplinks are being processed exactly as expected. However, this process takes an unexpected ammount of time (averaging around the 2-3 minute mark).
For my intended use cases this is far too long.

When tracing the Uplink frames I have determined the latency to originate from some where within the stf-core-stack (between the device shadow and S3 bucket. 

<details>
<summary>Reference architecture</summary>

![image](https://github.com/aws-samples/aws-stf-core-scorpio/blob/main/docs/images/referencearch.png)
</details>

<details>
<summary>Trace Logs</summary>

Data producer Lambda Function
![image](https://user-images.githubusercontent.com/84558754/222300155-501b033f-8821-4d80-b904-77e2c5feb625.png)

Update Shadow Lambda Function
![image](https://user-images.githubusercontent.com/84558754/222298695-53c95706-323f-4db0-8f92-ad833dafcd3b.png)

from here I have deduced that the issue is not within the shadow or IoT rule as the context broker update function is executed in a timely fashion.

Update broker Lambda Function
![image](https://user-images.githubusercontent.com/84558754/222299443-3286eec8-39a0-4a8f-9bdb-40241b67f937.png)

Then the bucket is finally available after a 144 second delay. (this delay is consistently 144 seconds across all uplinks)
Update broker Lambda Function

Bucket modification time
![image](https://user-images.githubusercontent.com/84558754/222299999-c88348ee-f7e1-41e2-9efd-d89f39a6588a.png)

</details>

Has anyone got any ideas as to why this might be so delayed, to appear in the storage bucket??
Any help will be greatly appreciated!

**Comment by alifrugal** [comment]
Hi, 

Thanks for the feedback!

The S3 bucket is intended to store historical data and not to fetch real-time data from. The latency you mentioned is on purpose and it's part of the batching strategy before storing in the S3 bucket. You define the batch interval or size in Kinesis Firehose (by default it's 60 seconds or 64 MBs - the first that happens). here: https://github.com/aws-samples/aws-stf-core-scorpio/blob/main/lib/stacks/stf-iot/stf-iot-core/index.ts

`
bufferingHints: {
  intervalInSeconds: 60,
  sizeInMBs: 64
},`

To consume real-time data, you have got multiple options: 

1) You can get the Thing and all its associated entities with: 
`{StfCoreEndpoint}/iot/things/{thingName}`. 
2) You can query the Context Broker: {StfCoreEndpoint}/ngsi-ld/v1/entities/{{entity}}
3) You can subscribe to the AWS IoT Core shadows using MQTT. 

Let me know if you got any other questions. 

Ali
